[package]
name        = "hologram-damogran-dyndns"
version     = "2.1.3"
description = "hologram: DynDNS setup for Damogran (using Gandi API)"
requires    = ["gandi-dyndns>=2015.12.26"]

[[file]]
path    = "/usr/share/holo/files/50-damogran/etc/gandi-dyndns/config.json"
content = """
    {
      "api_key": "${GANDI_APIKEY}",
      "domains": {
        "${DAMOGRAN_HTTP_PRIVATE_DOMAIN}": ["damogran","static"]
      }
    }
"""
[[symlink]]
path   = "/usr/share/holo/files/50-damogran-vars/etc/gandi-dyndns/config.json.holoscript"
target = "/my/variables"

[[file]]
path    = "/usr/lib/systemd/system/gandi-dyndns.timer"
content = """
    [Unit]
    Description=Check and update DNS entries every five minutes
    After=network-online.target
    Wants=network-online.target

    [Timer]
    OnBootSec=1min
    OnUnitActiveSec=5min

    [Install]
    WantedBy=timers.target
"""

[[symlink]]
path   = "/etc/systemd/system/timers.target.wants/gandi-dyndns.timer"
target = "/usr/lib/systemd/system/gandi-dyndns.timer"
