[package]
name    = "hologram-base"
version = "20160415.1"
description = "hologram: base installation"

requires = [
    "group:base", "except:netctl",
    "hologram-disable-cacert",
    "hologram-openssh",
    # assorted CLI tools
    "ack",
    "acpi",
    "atop",
    "dnsutils",
    "dosfstools",     # mkfs.vfat
    "git",
    "gptfdisk",
    "hdparm",
    "htop",
    "inotify-tools",
    "iperf",
    "irssi",
    "iw",
    "lsof",
    "neovim",
    "net-tools",      # netstat
    "nmap",           # ncat
    "optipng",
    "pacgraph",
    "pwgen",
    "pwget",
    "p7zip",
    "smartmontools",
    "rsync",
    "screen",
    "strace",
    "sshfs",
    "sudo",
    "tcpdump",
    "traceroute",
    "tree",
    "units",
    "unrar",
    "unzip",
    "vim-minimal",
    "wget",
    "whois",
    "yaourt",
    "zip",
    "zsh",
]

definitionFile = "/usr/share/holo/users-groups/00-base.toml"
setupScript    = "locale-gen"

# entities
[[group]]
name    = "sudo"
system  = true

[[user]]
name    = "stefan"
comment = "Stefan Majewsky"
uid     = 1001
group   = "users"
groups  = ["sudo"]
shell   = "/bin/zsh"

# locale
[[file]]
path    = "/etc/locale.conf"
content = """
    LANG=de_DE.UTF-8
    LC_MESSAGES=C
"""

[[file]]
path    = "/usr/share/holo/files/00-base/etc/locale.gen"
content = """
    de_DE.UTF-8 UTF-8
    en_US.UTF-8 UTF-8
"""

[[symlink]]
path   = "/etc/localtime"
target = "/usr/share/zoneinfo/Europe/Berlin"

[[file]]
path    = "/etc/vconsole.conf"
content = """
    KEYMAP=de-latin1-nodeadkeys
"""

# filesystem
[[file]]
path    = "/usr/share/holo/files/00-base/etc/fstab.holoscript"
mode    = "0755"
content = """
    #!/bin/sh
    cat
    # the following file should be generated at install time with genfstab
    cat /etc/fstab.local || exit 1
"""

# pacman
[[file]]
path    = "/usr/share/holo/files/00-base/etc/pacman.conf.holoscript"
mode    = "0755"
content = '''
    #!/bin/sh
    sed '
        # enable additional options
        s/^#\(Color\|VerbosePkgLists\)$/\1/

        # enable multilib repo (TODO: move this into a later hologram?)
        /^#\[multilib]/,/^$/s/^#//
    '

    # add official holo repo
    echo
    echo '[holo]'
    echo 'Server = https://repo.holocm.org/archlinux/$arch'

    # add holograms repo
    echo
    echo '[holograms]'
    echo 'Server = https://static.${DAMOGRAN_HTTP_PRIVATE_DOMAIN}/repo'
'''
[[symlink]]
path   = "/usr/share/holo/files/99-variables/etc/pacman.conf.holoscript"
target = "/my/variables"

[[file]]
path    = "/usr/share/holo/files/00-base/etc/pacman.d/mirrorlist.holoscript"
mode    = "0755"
content = """
    #!/bin/sh
    # choose some German mirrors randomly (rankmirrors is better, but slows down `holo apply` too much)
    sed '1,/^## Germany/d;s/^#Server/Server/;/^$/,$d' | sort -R
"""

# sudo
[[file]]
path    = "/usr/share/holo/files/00-base/etc/sudoers"
mode    = "0440"
content = """
    root    ALL=(ALL) ALL
    %sudo   ALL=(ALL) ALL

    Defaults env_keep+="http_proxy https_proxy ftp_proxy all_proxy socks_proxy no_proxy"
"""

# systemd-networkd
[[symlink]]
path   = "/etc/systemd/system/multi-user.target.wants/systemd-networkd.service"
target = "/usr/lib/systemd/system/systemd-networkd.service"
[[symlink]]
path   = "/etc/systemd/system/sockets.target.wants/systemd-networkd.socket"
target = "/usr/lib/systemd/system/systemd-networkd.socket"

# home directory including SSH keys
[[directory]]
path  = "/home/stefan"
mode  = "0700"
owner = 1001 # stefan
group = 100  # users

[[directory]]
path  = "/home/stefan/.ssh"
mode  = "0700"
owner = 1001 # stefan
group = 100  # users

# development environment bootstrapping
[[directory]]
path  = "/home/stefan.devenv"
mode  = "0700"
owner = 1001 # stefan
group = 100  # users

[[directory]]
path  = "/home/stefan.devenv/build"
owner = 1001 # stefan
group = 100  # users

[[file]]
path  = "/home/stefan.devenv/bootstrap.sh"
mode  = "0755"
owner = 1001 # stefan
group = 100  # users
content = """
    #!/bin/sh
    set -e
    if [ ! -d /home/stefan.devenv/repo/.git ]; then
        git clone https://github.com/majewsky/devenv.git /home/stefan.devenv/repo
    fi
    cd /home/stefan.devenv/repo
    ./setup.sh install-core
"""
