[package]
name        = "hologram-base-gui"
version     = "1.2.1"
description = "hologram: base GUI installation"

requires = [
    "hologram-base-gui-minimal",
    "hologram-multimedia-base",
    # assorted GUI apps
    "mesa-demos",
    "mumble",
    "paprefs",
    "pavucontrol",
    "pidgin-otr", # includes pidgin
    "thunderbird",
    "tk", # for gitk and git-gui
    "vlc",
    # font packages
    "cantarell-fonts",
    "otf-titillium",
    "ttf-freefont",
    "ttf-linux-libertine",
    "ttf-montserrat",
    "ttf-ubuntu-font-family",
]

[[file]]
path = "/usr/bin/munin-for"
mode = "0755"
contentFrom = "src/munin-for"
