[package]
name        = "hologram-secrets-empty"
version     = "1.0.0"
description = "hologram: placeholder for host's custom secrets package"

provides = [ "hologram-secrets" ]

# This package will be installed during initial system installation to satisfy
# the "hologram-secrets" requirement in hologram-base. Afterwards, a custom
# secrets package for the specific host can be installed which provides
# "hologram-secrets" and conflicts with "hologram-secrets-empty".
