[package]
name        = "hologram-kde-desktop"
version     = "1.0.12"
description = "hologram: GUI installation with KDE Plasma desktop"

requires = [
    "hologram-base-gui",
    # display manager
    "sddm",
    # desktop
    "group:plasma", "except:bluedevil", "except:plasma-nm", "except:ksshaskpass",
    "breeze-kde4",
    "except:breeze-gtk", # hilariously broken with GTK 3.20 ATM
    "gst-plugins-good",  # optional: for WebM support in qt5-webkit
    "mariadb",           # optional: for Akonadi
    # applications
    "ark",
    "dolphin",
    "gwenview",
    "filelight",
    "kcharselect",
    "kcolorchooser",
    "kdebase-kdialog",
    "kdeutils-kgpg",
    "kid3",
    "kmix",
    "kolourpaint",
    "konsole",
    "kruler",
    "kwalletmanager",
    "spectacle",
    "yakuake",
]

# TODO: kwallet-pam

[[file]]
path    = "/etc/sddm.conf"
content = """
    [Autologin]
    User=stefan
    Session=plasma.desktop

    [Theme]
    Current=breeze
"""

[[symlink]]
path   = "/etc/systemd/system/display-manager.service"
target = "/usr/lib/systemd/system/sddm.service"
