[package]
name        = "hologram-sway-desktop"
version     = "0.0.3"
description = "hologram: Wayland desktop using Sway compositor and selected KDE apps"

requires = [
  "hologram-base-gui-minimal",
  "sway",
  # selected KDE appliations
  "filelight",
  "kcharselect",
  "kcolorchooser",
  "kolourpaint",
  "konsole",
  "kruler",
]

[[file]]
path    = "/usr/share/holo/files/30-sway-desktop/etc/sddm.conf"
content = """
    [Autologin]
    User=stefan
    Session=sway.desktop

    [Theme]
    Current=breeze
"""

[[file]]
path = "/usr/share/holo/files/30-sway-desktop/etc/sway/config"
contentFrom = "src/sway.cfg"
