[package]
name        = "hologram-docker"
version     = "1.0.0"
description = "hologram: Install and start Docker"
requires    = ["docker"]

[[user]]
name   = "stefan"
groups = ["docker"]

[[symlink]]
path   = "/etc/systemd/system/multi-user.target.wants/docker.service"
target = "/usr/lib/systemd/system/docker.service"
