[package]
name        = "hologram-automation"
version     = "0.3.3"
description = "hologram: infrastructure for dialog-based task automation and common tasks"

requires = [
    "pipexec",
    "xmpp-bridge",
]

[[file]]
path = "/usr/bin/with-xmpp-bridge"
mode = "0700"
# TODO: pipexec does not propagate a non-zero exit code from its children
content = '''
    #!/bin/bash
    set -e

    # ensure that only one XMPP user runs at a time
    exec 9>/run/xmpp-bridge.lock
    flock 9

    source /my/xmpp   # sets the environment variables for xmpp-bridge(1)
    pipexec -- [ A "$@" ] [ B /usr/bin/peet 2 3 ] [ C /usr/bin/xmpp-bridge ] \
        "{A:1>B:2}" "{A:2>B:3}" "{B:1>C:0}" "{C:1>A:0}"
'''

################################################################################
# task: guided system upgrade

[[file]]
path = "/usr/lib/automation/upgrade.sh"
mode = "0755"
contentFrom = "src/automation-upgrade.sh"

[[file]]
path = "/usr/lib/systemd/system/auto-upgrade.service"
content = '''
    [Unit]
    Description=Guided automatic system upgrade
    After=multi-user.target
    Wants=multi-user.target

    [Service]
    Type=oneshot
    ExecStart=/usr/bin/with-xmpp-bridge /usr/lib/automation/upgrade.sh
'''

[[file]]
path = "/usr/lib/systemd/system/auto-upgrade.timer"
content = '''
    [Unit]
    Description=Guided automatic system upgrade

    [Timer]
    OnCalendar=15:00:00

    [Install]
    WantedBy=timers.target
'''

[[symlink]]
path   = "/etc/systemd/system/timers.target.wants/auto-upgrade.timer"
target = "/usr/lib/systemd/system/auto-upgrade.timer"

################################################################################
# task: health check (periodically, and immediately after a reboot)

[[file]]
path = "/usr/lib/automation/health.sh"
mode = "0755"
contentFrom = "src/automation-health.sh"

[[file]]
path = "/usr/lib/systemd/system/auto-health.service"
content = '''
    [Unit]
    Description=Automatic system health check
    After=multi-user.target
    Wants=multi-user.target

    [Service]
    Type=oneshot
    ExecStart=/usr/bin/with-xmpp-bridge /usr/lib/automation/health.sh
'''

[[file]]
path = "/usr/lib/systemd/system/auto-health.timer"
content = '''
    [Unit]
    Description=Automatic system health check

    [Timer]
    OnStartupSec=1min
    OnCalendar=17:00:00

    [Install]
    WantedBy=timers.target
'''

[[symlink]]
path   = "/etc/systemd/system/timers.target.wants/auto-health.timer"
target = "/usr/lib/systemd/system/auto-health.timer"
