[package]
name        = "hologram-minecraft-server"
version     = "0.1.0"
description = "hologram: Minecraft server"

requires = [
    "jre8-openjdk-headless",
]

################################################################################
# user account for running Minecraft

[[user]]
name  = "minecraft"
home  = "/home/minecraft"
shell = "/bin/bash"
uid   = 1002
group = "users"

[[file]]
path = "/usr/share/holo/ssh-keys/minecraft/keys.pub"
content = '''
    command="/home/minecraft/bin/minecraftServerLauncher.sh",no-port-forwarding,no-X11-forwarding,no-agent-forwarding,no-pty ssh-rsa  AAAAB3NzaC1yc2EAAAADAQABAAACAQClzW34zaEtGvGpIf4jRRQVnwNLv+nKBhqvW04ggh4fF9ILXvHBnjW3klfwlP9JmSCHK9IJSAsGS9jMZ7ckbgFMir4AJXvZYMlLY7PyuECF7OqOjSCmQGKdhmfnVz7HUrOBNrWM+Kz/KV76jtmxZlRI7gsX0RlZ+EXyjoUm4pA1l3085Pvsl7QXWJQQrbBl83IF/G7QYYGXtmaFXuqDbitj0d5yT01wgawWivlmitEWBUILTjS5pk4OyUlzzebjmd77jZQOenIqEg6ZNtoAludMl2jvxtH9TrCrv+XQh65GoV0dT0gROvG4H4aH7Yh7bxRkBci5G9QvcoRaURNUyjGVQqr8Bm9pfcJEzJa6qN+5RU2IA9WeE1MSaH6imvmU0XMEfJiK0qF//OhXAAoKeVCFu3rJAUIXfViW+EaxTnZlx+NXDmF57Z2ZgA7zxFdmuPhW/ogciDX+g0yMBbKmCURUh4tzhNlCbFksI4io48jXpTDfxVaCJfuzpHCFdxnt+DxQlKE4s4N3Mo+tXna++KP1MWYOjiCm/RTneDzXje1I0+ODNVMNuCaYAMKwqpc3W0d27DuplT4+vILUXCwfdEr3WZabYQH6+n13OKbVTvtuMwBjyZf4g9/wI8UNKRxGJZM87f4hGFbp+2eewIThPDN0CI3rwPUcKh73l8lMNJvXKw== stefan@arcturus
    command="/home/minecraft/bin/minecraftServerLauncher.sh",no-port-forwarding,no-X11-forwarding,no-agent-forwarding,no-pty ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC5SglxtK6N9Gfqcly/k5ozXSw4YIcmaWdsXnO40cEZWttTU0uuGxjhJQ2uppW7isHdgv9klQnJ8CE/tJ59i+JC8Hw3lZKYjO4MGEYBAWiEdh6fkszAmE7uDbFz4BpXuLd5f51fB4KlBUxvfq5ty5LSy6lCBUdn9UTO7NUTC/Bi7te3oxPCppHUOz5F/SmKyqrI/lCjhDXBIPUu1JSC38483FWWeZO/YPnoxtEbh9xPcKNeklUIkb03+zFRBsEmpLzSMBaIKDu884HZPK7jVLdthztKKFVLn/n1a6qk64mVm/QG1C+pJV93k+PdhWEXq3oHltYDDgCkaT8Ll//2XacAIP2CE7NTqjrCuNrq6u0yE7xjKj9PhpL1/jl5/4M173bxMv/x8ktK1iIKH0L+VfSj8JzhxIZVF7c9FQm9v4vLk0kcDyQKgnImfkotJjnS1y1HdseIFVogJb1lIz2NDdzB0/nRNZMky4yMTKZyx8vhA+6W9elFu2ofB8g7ONvDaKiMR7dBWE6ScB0tCvmJdygzlHqUzTiMKUUwZ+4EbNkYPchmFOs9COMkUzZ+BvmH/WM2LpGS7fJNXc7ygScrvZaNOxHm3ZEQHWCn3cOE9wBzOKwATimOVRc4f870ZHDyHkMCQVQwfQfKjrlwFIg+rFKWQ7qB1EzM3JxtovBYTIHHcw== stefan@krikkit
    command="/home/minecraft/bin/minecraftServerLauncher.sh",no-port-forwarding,no-X11-forwarding,no-agent-forwarding,no-pty ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAgEAtD1Wf7vCrS8iQwDS3D+qt8WS2hOdLGUTz8XkjX4vDs5wBvcwvvUXnChSMJNYLQFuSw49XlasfGaDeZsPX+CUH/hozQF4y9TIy+/RinaA0rWFiEok6xB3trmcTDYMi43PxZqBqy5HIK0mhKEbCRcp9FNB5qhLKxOphARfXFtGPo2BulLpZpnTMFE6jJrWylcXOkb3C4+A/e71ztO8hwYemPWoYl0lqJMtPS1KoifjIpEWW5JkcvmS2MbXBAfKf/97YtXDBiLh4WRA8BsKM8/V0ZxNOpeCwxVs9lQMCkBzl7374A4OjAEbh7ie3BDr9IEYH4ofH+aAaO05IUsbCZvGn55dhCt+T1L7a9jDd6RsUJwazOHalqCXqN/4imEzhSFYE6B5QdbhqHL6+mhKG3SenjSWv49hvEojU/7XohLPvBgnvupTNktjDTBG+fUfuL2XbJRZ91d6tYZkjmlmNJox6dNE4WzHLd73WywUW3s7OxWIaz8vBvnIlRxXVSbG/Irxq7YPx7+L/rFsj55cchD2FEbgtBfbNiG88/49WyK3M+5yzX7fTdNPVMeNjEYA1A6+eqU0LauOejTA9Zp7ernBjl40i/lXSectBipZFUL7azRSE7RzY53Y7CeLS68HrmVos3mSO0rMU/Fk11xHodImgH/KbjNiIeArAq6uYRi7eRk= apophis@schlepptop
    command="/home/minecraft/bin/minecraftServerLauncher.sh",no-port-forwarding,no-X11-forwarding,no-agent-forwarding,no-pty ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBuoAQ9uQayjVuvFwnfV+pXrauYIvge6DGk9gdapIhoO apophis@toruk
    command="/home/minecraft/bin/minecraftServerLauncher.sh",no-port-forwarding,no-X11-forwarding,no-agent-forwarding,no-pty ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCs0PiLBRaS63NBDLYhXDzIvKT2a6rHbiosOiKIjjiOpn5LLZZPgaOfghp3z38ZwiUC5b3peL86TFC905zYU7KXXAoOGRVAT7dn+emCPcGn6164K2nDPGA1GvZP7gS2gUhvrxmDw66ilt32WWTyf4Xv5xwyOO8S0a98jc+MAib9ksETciea3XSAVswKUCG3SAR1KIru7qNPaPuGxu6QWQEjZgjkHTZ0IL7v82cNm/XxtTKtJDa4LRegxNUJBYOuz36C8kx6mlM3Y4K+d5eevOJKKjlldr2NWj+3GJbpV2ItO6fed/MzMCJLep61l5Fvr4RHWFZhHaPJ7QkUrqBnX4Kn felix
'''

[[file]]
path = "/home/minecraft/bin/minecraftServerLauncher.sh"
content = '''
#!/bin/bash

# CONFDIR="$HOME/.minecraftServerLauncher/"
# if [ ! -d "$CONFDIR" ]; then
# 	mkdir "$CONFDIR"
# fi

CONFFILE="$HOME/.minecraftServerLauncherrc"
if [ -f "$CONFFILE" ]; then
	. "$CONFFILE"
else
	SERVERROOT="$HOME/minecraft"
fi

STATEFILE="$XDG_RUNTIME_DIR/minecraftServerState"
LOCKFILE="$XDG_RUNTIME_DIR/minecraftServerLock"

# always call this when exiting after a lock was aquired to ensure it is
# cleaned-up properly
exitHandler()
{
	rm "$LOCKFILE"
	flock -u 9
	# echo EXIT
	if [ -z "$1" ]; then
		exit 0
	else
		exit $1 || exit 1
	fi
}

showAvail()
{
	echo "Available Servers:"
	ls "$SERVERROOT"
}

lock()
{
	exec 9> "$LOCKFILE"
	if ! flock -n 9 ; then
		echo "Locked by other process."
		exit 1
	fi
}

getState()
{
	if [ ! -f "$STATEFILE" ]; then
		CURRENTSERVER=""
	else
		CURRENTSERVER=$( cat "$STATEFILE" )
		set $CURRENTSERVER
		CS_NAME=$1
		CS_PID=$2
	fi
}

trap exitHandler SIGINT
trap exitHandler SIGTERM

if [ ! -z $SSH_ORIGINAL_COMMAND ]; then
	set $SSH_ORIGINAL_COMMAND
fi
CMD=$1
shift
ARGS=$@

getState

if [ -z "$CURRENTSERVER" ]; then
	echo "No Server running."
else
	echo "Currently running server: $CURRENTSERVER"
fi

showAvail

CMDS_HELP="Available commands: ( stop ) ( start [servername] ) ( logs )"
if [ -z "$CMD" ]; then
	echo "$CMDS_HELP"
	exit 0
fi

case "$CMD" in
	stop)
		if [ "$ARGS" != "-f" ]; then
			lock
		fi
		getState
		if [ -z "$CURRENTSERVER" ]; then
			echo "stop: No server running."
			exitHandler 1
		fi
		echo "stop Shutting down server $CURRENTSERVER"
		kill -s SIGTERM $CS_PID
		rm $STATEFILE
		CURRENTSERVER=""
		;;
	start)
		lock
		getState
		S_NAME="$ARGS"
		if [ ! -d "$SERVERROOT/$S_NAME" ]; then
			echo Invalid server name $S_NAME
			showAvail
			exitHandler 1
		fi
		if [ ! -z "$CURRENTSERVER" ]; then
			if [ "$CS_NAME" = "$S_NAME" ]; then
				echo Server $S_NAME slready running.
				exitHandler 0
			else
				echo Shutting down running server.
				kill -s SIGTERM $CS_PID
			fi
		fi
		cd "$SERVERROOT/$S_NAME/Server Files/" || exit 1
		/bin/sh "ServerStart.sh" >& log  &
		CS_PID=$!
		CS_NAME=$S_NAME
		CURRENTSERVER="$CS_NAME $CS_PID"
		echo "start: $CURRENTSERVER"
		echo "$CURRENTSERVER" > "$STATEFILE"
		;;
	logs)
		if [ -z "$CURRENTSERVER" ]; then
			echo "No Server running"
		else
			tail -f "$SERVERROOT/$CS_NAME/Server Files/log"
		fi
		;;
	*)
		echo "Invalid command: $CMD"
		echo "$CMDS_HELP"
		exit 1
		;;
esac

exitHandler 0
'''
