[package]
name        = "hologram-base-gui"
version     = "1.0.12"
description = "hologram: base GUI installation"

requires = [
    "hologram-base-gui-minimal",
    "hologram-multimedia-base",
    # assorted GUI apps
    "cutegram",
    "gnaural",
    "gnaural-presets",
    "mesa-demos",
    "mumble",
    "paprefs",
    "pavucontrol",
    "pidgin-otr", # includes pidgin
    "thunderbird",
    "tk", # for gitk and git-gui
    "vimprobable2",
    "vlc",
    # helper packages
    "gstreamer0.10-ffmpeg",
    # font packages
    "cantarell-fonts",
    "otf-titillium",
    "ttf-freefont",
    "ttf-linux-libertine",
    "ttf-montserrat",
    "ttf-oxygen",
    "ttf-ubuntu-font-family",
]
