[package]
name        = "hologram-wireguard-server"
version     = "0.2.2"
description = "hologram: Wireguard configuration for servers with public IPs"

requires = [
  "etcd",
  "secrets", # this uses /usr/bin/replicator
  "wireguard-dkms",
  "wireguard-tools",
]

[[directory]]
path = "/etc/wireguard"
mode = "0700" # contains private keys

# open port when using hologram-ferm
[[file]]
path    = "/etc/ferm.d/incoming-wireguard"
content = "proto udp dport {{.Vars.wg.port}} ACCEPT;"
[[symlink]]
path   = "/usr/share/holo/files/20-wireguard/etc/ferm.d/incoming-wireguard.holoscript"
target = "/usr/bin/replicator"

[[file]]
path    = "/etc/ferm.d/incoming-wirewrap"
content = "proto tcp dport {{.Vars.wg.port}} ACCEPT;"
[[symlink]]
path   = "/usr/share/holo/files/20-wireguard/etc/ferm.d/incoming-wirewrap.holoscript"
target = "/usr/bin/replicator"

################################################################################
# setup network between servers (x.y.1.0/24)

[[file]]
path = "/etc/wireguard/wg-server.conf"
content = '''
  [Interface]
  Address = {{.Vars.wg.slash16}}.1.{{.Vars.host.id}}/32
  PrivateKey = {{.Vars.wg.private_key}}
  ListenPort = {{.Vars.wg.port}}

  {{range $hostname, $cfg := .Vars.wg.peers}}
  {{- if $cfg.endpoint}}
  {{- if ne $hostname $.Vars.host.name}}
  [Peer]
  PublicKey = {{$cfg.public_key}}
  PresharedKey = {{$.Vars.wg.preshared_key}}
  Endpoint = {{$cfg.endpoint}}:{{$.Vars.wg.port}}
  AllowedIPs = {{$.Vars.wg.slash16}}.1.{{$cfg.machine_id}}/32

  {{- end}}
  {{- end}}
  {{- end}}
'''
[[symlink]]
path   = "/usr/share/holo/files/20-wireguard/etc/wireguard/wg-server.conf.holoscript"
target = "/usr/bin/replicator"

[[symlink]]
path   = "/etc/systemd/system/multi-user.target.wants/wg-quick@wg-server.service"
target = "/usr/lib/systemd/system/wg-quick@.service"

################################################################################
# etcd cluster between servers for Wirewrap leader election

[[directory]]
path  = "/var/lib/etcd"
owner = "etcd"
group = "etcd"

[[file]]
path    = "/usr/share/holo/files/20-etcd/etc/conf.d/etcd"
content = '''
  ETCD_NAME={{.Vars.host.name}}
  ETCD_DATA_DIR=/var/lib/etcd

  ETCD_LISTEN_PEER_URLS="http://{{.Vars.wg.slash16}}.1.{{.Vars.host.id}}:2380"
  ETCD_LISTEN_CLIENT_URLS="http://{{.Vars.wg.slash16}}.1.{{.Vars.host.id}}:2379"
  ETCD_ADVERTISE_CLIENT_URLS="http://{{.Vars.wg.slash16}}.1.{{.Vars.host.id}}:2379"

  ETCD_INITIAL_ADVERTISE_PEER_URLS="http://{{.Vars.wg.slash16}}.1.{{.Vars.host.id}}:2380"
  ETCD_INITIAL_CLUSTER_TOKEN="wirewrap-etcd"
  ETCD_INITIAL_CLUSTER_STATE="new"
  ETCD_INITIAL_CLUSTER="{{range $hostname, $cfg := .Vars.wg.peers -}}
    {{- if $cfg.endpoint -}}
      {{$hostname}}=http://{{$.Vars.wg.slash16}}.1.{{$cfg.machine_id}}:2380,
    {{- end -}}
  {{- end}}"

  # values in ms
  ETCD_HEARTBEAT_INTERVAL=100
  ETCD_ELECTION_TIMEOUT=1000
'''
[[symlink]]
path   = "/usr/share/holo/files/20-etcd/etc/conf.d/etcd.holoscript"
target = "/usr/bin/replicator"

[[symlink]]
path   = "/etc/systemd/system/multi-user.target.wants/etcd.service"
target = "/usr/lib/systemd/system/etcd.service"

# etcd is restricted to the server VPN
[[file]]
path    = "/etc/ferm.d/incoming-etcd"
content = '''
  proto tcp dport (etcd-client etcd-server) interface wg-server ACCEPT;
'''

# make etcdctl work
[[file]]
path    = "/etc/profile.d/etcdctl.sh"
content = '''
  export ETCDCTL_API=3
  export ETCDCTL_ENDPOINTS="http://{{.Vars.wg.slash16}}.1.{{.Vars.host.id}}:2379"
'''
[[symlink]]
path   = "/usr/share/holo/files/20-etcd/etc/profile.d/etcdctl.sh.holoscript"
target = "/usr/bin/replicator"

################################################################################
# setup network between everyone (x.y.2.0/24) with Wirewrap

[[file]]
path = "/etc/wireguard/wirewrap.conf"
content = '''
  [Interface]
  Address = {{.Vars.wg.slash16}}.2.{{.Vars.host.id}}/32
  PrivateKey = {{.Vars.wg.private_key}}
  ListenPort = {{.Vars.wg.port}}

  {{range $hostname, $cfg := .Vars.wg.peers}}
  [Peer]
  PublicKey = {{$cfg.public_key}}
  PresharedKey = {{$.Vars.wg.preshared_key}}
  AllowedIPs = {{$.Vars.wg.slash16}}.2.{{$cfg.machine_id}}/32
  {{if $cfg.endpoint -}}
  WirewrapID = h2g2
  Endpoint = {{$cfg.endpoint}}:{{$.Vars.wg.port}}
  {{end}}
  {{- end}}

  [Wirewrap]
  ID = h2g2
  Etcd = {{.Vars.wg.slash16}}.1.{{.Vars.host.id}}:2379
'''
[[symlink]]
path   = "/usr/share/holo/files/20-wireguard/etc/wireguard/wirewrap.conf.holoscript"
target = "/usr/bin/replicator"
