[package]
name        = "holodeck-magrathea"
version     = "1.0.0"
description = "holodeck: services on Magrathea (traveling Minecraft LAN server)"

requires = [
    "hologram-base-accessible",
    "hologram-uefi-bootloader",
    # for Minecraft
    "jre8-openjdk-headless",
    # optional: tools for initial setup via Wifi
    "dhcpcd",
    "wpa_supplicant",
]

[[file]]
path    = "/etc/hostname"
content = "magrathea"

[[file]]
path    = "/etc/profile.d/prettyprompt.sh"
content = """
export PRETTYPROMPT_COMMONUSER=stefan
export PRETTYPROMPT_HOSTCOLOR='0;31'
"""

# network setup: systemd-networkd and systemd-resolved

[[file]]
path    = "/etc/systemd/network/lan.network"
content = """
    [Match]
    Name=en*

    [Network]
    DHCP=yes

    [Address]
    Address=10.0.0.42/24

    [Address]
    Address=192.168.0.42/24

    [Address]
    Address=192.168.1.42/24
"""

[[symlink]]
path   = "/etc/systemd/system/multi-user.target.wants/systemd-resolved.service"
target = "/usr/lib/systemd/system/systemd-resolved.service"

[[symlink]]
path   = "/usr/share/holo/files/50-magrathea/etc/resolv.conf"
target = "/run/systemd/resolve/resolv.conf"
