[package]
name    = "hologram-base"
version = "20161019.1"
description = "hologram: base installation"

requires = [
    "hologram-openssh",
    "a-decision-regarding-cacert", # usually provided by hologram-disable-cacert
    # group:base, but remove the stuff that I don't usually need on remote systems
    "group:base",
    "except:inetutils",
    "except:jfsutils",
    "except:licenses",
    "except:lvm2",
    "except:mdadm",
    "except:nano",
    "except:netctl",
    "except:pciutils",
    "except:pcmciautils",
    "except:reiserfsprogs",
    "except:sysfsutils",
    "except:usbutils",
    "except:xfsprogs",
    # assorted CLI tools
    "ack",
    "dnsutils",
    "git",
    "gptfdisk",
    "htop",
    "inxi",
    "lsof",
    "net-tools",      # netstat
    "nmap",           # ncat
    "pwgen",
    "rsync",
    "screen",
    "strace",
    "sudo",
    "tcpdump",
    "traceroute",
    "tree",
    "units",
    "vim",
    "wget",
    "zsh",
]

# entities
[[group]]
name    = "sudo"
system  = true

[[user]]
name    = "stefan"
comment = "Stefan Majewsky"
uid     = 1001
group   = "users"
groups  = ["sudo"]
shell   = "/bin/zsh"

# locale
[[file]]
path    = "/etc/locale.conf"
content = """
    LANG=de_DE.UTF-8
    LC_MESSAGES=C
"""

[[file]]
path    = "/usr/share/holo/files/00-base/etc/locale.gen"
content = """
    de_DE.UTF-8 UTF-8
    en_US.UTF-8 UTF-8
"""

[[action]]
on     = "setup"
script = "locale-gen"

[[symlink]]
path   = "/etc/localtime"
target = "/usr/share/zoneinfo/Europe/Berlin"

[[file]]
path    = "/etc/vconsole.conf"
content = """
    KEYMAP=de-latin1-nodeadkeys
"""

# filesystem
[[file]]
path    = "/usr/share/holo/files/00-base/etc/fstab.holoscript"
mode    = "0755"
content = """
    #!/bin/sh
    cat
    # the following file should be generated at install time with genfstab
    cat /etc/fstab.local || exit 1
"""

# pacman
[[file]]
path    = "/usr/share/holo/files/00-base/etc/pacman.conf.holoscript"
mode    = "0755"
content = '''
    #!/bin/sh

    # skip installation of translations
    echo '[options]'
    echo 'NoExtract = usr/share/locale/*/LC_MESSAGES'
    echo 'NoExtract = usr/share/locale/*/LC_MESSAGES/*'

    sed '
        # enable additional options
        s/^#\(Color\|VerbosePkgLists\)$/\1/

        # enable multilib repo (TODO: move this into a later hologram?)
        /^#\[multilib]/,/^$/s/^#//
    '

    # add official holo repo
    echo
    echo '[holo]'
    echo 'Server = https://repo.holocm.org/archlinux/$arch'

    # add holograms repo
    echo
    echo '[holograms]'
    echo 'Server = https://repo.holocm.org/archlinux/personal'
'''

[[file]]
path    = "/usr/share/holo/files/00-base/etc/pacman.d/mirrorlist.holoscript"
mode    = "0755"
content = """
    #!/bin/sh
    # prefer my own mirror
    echo 'Server=https://mirror.bethselamin.de/$repo/os/$arch'
    # other German mirrors (no shuffling or ranking since this is only a fallback anyway)
    sed '1,/^## Germany/d;s/^#Server/Server/;/^$/,$d'
"""

# sudo
[[file]]
path    = "/usr/share/holo/files/00-base/etc/sudoers"
mode    = "0440"
content = """
    root    ALL=(ALL) ALL
    %sudo   ALL=(ALL) ALL

    Defaults env_keep+="http_proxy https_proxy ftp_proxy all_proxy socks_proxy no_proxy"
"""

# systemd-networkd
[[symlink]]
path   = "/etc/systemd/system/multi-user.target.wants/systemd-networkd.service"
target = "/usr/lib/systemd/system/systemd-networkd.service"
[[symlink]]
path   = "/etc/systemd/system/sockets.target.wants/systemd-networkd.socket"
target = "/usr/lib/systemd/system/systemd-networkd.socket"

# home directory including SSH keys
[[directory]]
path  = "/home/stefan"
mode  = "0700"
owner = 1001 # stefan
group = 100  # users

[[directory]]
path  = "/home/stefan/.ssh"
mode  = "0700"
owner = 1001 # stefan
group = 100  # users

# development environment bootstrapping
[[directory]]
path  = "/home/stefan.rtree"
mode  = "0700"
owner = 1001 # stefan
group = 100  # users

[[directory]]
path  = "/home/stefan.devenv"
mode  = "0700"
owner = 1001 # stefan
group = 100  # users

[[directory]]
path  = "/home/stefan.devenv/build"
owner = 1001 # stefan
group = 100  # users

[[file]]
path  = "/home/stefan.devenv/bootstrap.sh"
mode  = "0755"
owner = 1001 # stefan
group = 100  # users
content = """
    #!/bin/sh
    set -e
    if [ ! -d /home/stefan.devenv/repo/.git ]; then
        git clone https://github.com/majewsky/devenv.git /home/stefan.devenv/repo
    fi
    cd /home/stefan.devenv/repo
    ./setup.sh install-core
"""
