[package]
name        = "hologram-base-gui-minimal"
version     = "1.1.0"
description = "hologram: base GUI installation (variant for space-constrained systems)"

requires = [
    "hologram-base-accessible",
    "xorg-server",
    # assorted GUI apps
    "group:xorg-apps",
    "firefox",
    "graphviz",
    "gnuplot",
    "gvim", # vim with X11 clipboard support
    "inkscape",
    "mupdf",
    "qgit",
    "quickstart",
    "screen-message",
    "sxiv",
    "xsel",
    # helper packages
    "aspell-de",  # to silence complaints in gitk about missing spell check dict
    "human-icon-theme",
    # font packages
    "adobe-source-code-pro-fonts",
    "adobe-source-sans-pro-fonts",
    "adobe-source-serif-pro-fonts",
    "ttf-bitstream-vera",
    "ttf-dejavu",
    "ttf-droid",
    "ttf-freefont",
    "ttf-liberation",
]

# install a custom X11 keymap addon (see comments in src/xkb/symbols.txt)

[[file]]
path = "/usr/share/X11/xkb/symbols/stefan"
contentFrom = "src/xkb/symbols.txt"

[[file]]
path = "/usr/share/holo/files/00-base/usr/share/X11/xkb/rules/base.holoscript"
mode = "0755"
contentFrom = "src/xkb/rules.holoscript"

[[file]]
path = "/usr/share/holo/files/00-base/usr/share/X11/xkb/rules/base.lst.holoscript"
mode = "0755"
contentFrom = "src/xkb/rules.lst.holoscript"

[[file]]
path = "/usr/share/holo/files/00-base/usr/share/X11/xkb/rules/base.xml.holoscript"
mode = "0755"
contentFrom = "src/xkb/rules.xml.holoscript"

[[file]]
path = "/usr/share/holo/files/00-base/usr/share/X11/xkb/rules/evdev.holoscript"
mode = "0755"
contentFrom = "src/xkb/rules.holoscript"

[[file]]
path = "/usr/share/holo/files/00-base/usr/share/X11/xkb/rules/evdev.lst.holoscript"
mode = "0755"
contentFrom = "src/xkb/rules.lst.holoscript"

[[file]]
path = "/usr/share/holo/files/00-base/usr/share/X11/xkb/rules/evdev.xml.holoscript"
mode = "0755"
contentFrom = "src/xkb/rules.xml.holoscript"
