[package]
name        = "hologram-damogran-audio"
version     = "1.3.1"
description = "hologram: PulseAudio and MPD service for Damogran"
requires    = [
    "mpd",
    "pulseaudio",
    "pulseaudio-zeroconf",
]

# we place various stuff in /home/pulse; fix ownership in one step
setupScript = "chown -R pulse:pulse /home/pulse"

# create "pulse" user and group, with a lingering user session that ensures
# that services come up automatically on boot
[[group]]
name    = "pulse"
system  = true

[[user]]
name    = "pulse"
comment = "PulseAudio user"
group   = "pulse"
groups  = ["audio"]

[[directory]]
path = "/home/pulse"
mode = "0700"
# owner and group are set in one step in the custom setupScript above

[[file]]
path        = "/var/lib/systemd/linger/pulse"
contentFrom = "/dev/null" # empty file

# enable network access for PulseAudio

[[file]]
path = "/usr/share/holo/files/50-damogran/etc/pulse/default.pa.holoscript"
mode = "0755"
content = """
#!/bin/sh
    cat
    echo 'load-module module-native-protocol-tcp auth-ip-acl=127.0.0.1;10.0.0.0/8 auth-anonymous=1'
    echo 'load-module module-zeroconf-publish'
"""

# start PulseAudio as a user service, restart automatically if PulseAudio
# decides to exit after the last network client disconnects (it needs to be
# running at all times for network discovery to work)

[[symlink]]
path   = "/home/pulse/.config/systemd/user/sockets.target.wants/pulseaudio.socket"
target = "/usr/lib/systemd/user/pulseaudio.socket"

[[symlink]]
path   = "/home/pulse/.config/systemd/user/default.target.wants/pulseaudio.service"
target = "/usr/lib/systemd/user/pulseaudio.service"

[[file]]
path = "/home/pulse/.config/systemd/user/pulseaudio.service.d/restart.conf"
content = """
    [Service]
    Restart=always
"""

# start MPD as a user service, too

[[symlink]]
path   = "/home/pulse/.config/systemd/user/default.target.wants/mpd.service"
target = "/usr/lib/systemd/user/mpd.service"

[[directory]]
path = "/home/pulse/.mpd"

[[file]]
path    = "/home/pulse/.mpdconf"
content = """
    music_directory    "/raid/data/Musik"
    playlist_directory "~/.mpd/playlists"
    db_file            "~/.mpd/database"
    log_file           "syslog"
    pid_file           "~/.mpd/pid"
    state_file         "~/.mpd/state"
    sticker_file       "~/.mpd/sticker.sql"

    # access is limited to intranet by iptables
    bind_to_address    "any"

    audio_output {
        type "pulse"
        name "PulseAudio"
    }

    filesystem_charset "UTF-8"
"""
