[package]
name        = "hologram-disable-cacert"
version     = "1.0.1"
description = "Disable CACert root certificate"
provides    = [ "ca-certificates-cacert", "a-decision-regarding-cacert" ]
conflicts   = [ "ca-certificates-cacert" ]
