[package]
name        = "hologram-base-hetzner"
version     = "1.0.6"
description = "hologram: configuration for my servers hosted by hetzner.de"

requires = [
    "hologram-base",
    "haveged",
]

# authorized SSH keys
[[file]]
path    = "/usr/share/holo/ssh-keys/stefan/hetzner.pub"
content = """
    ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC35KpWLuaB6Tf/rpm4ofIhfoBxYxsTxo/WWFZvvM7XSQmn1Z99AbidZvQZnc3kRmS3epo42oGjTLVmnEWKt2RcDNgxfbR8jZ5CYmy2ZQUYBM/S63dG1b4msRUIdlP3oBWqk2393/ZDMt54F8voN6e5kk7K+Sca4JxZGRzTp6xVW2DExKioK/AFwxqBHuBRJ0Nr725nI4h1wGz6ZdxKbDS3rTiPIe9bjrt97e4XaqUlQKVi6MiMfr8TBCWXQkPcahYIuHsn6MBhTSv6/lr5IDzKhwBE1ZC8muNxbsCfUxG6VeNKD9q5cnQ3fSZOpWvjMaWdng4Wa2EHk98PDHKLIEL/doeEfmR7SwsLDk6vM8YOPVj51C4C2KWzm6ZCnRzfBNrX9+SmiELKeJ35Qwg25P5wUWWmL+EgmR8CXZyHlBeqc9V1LDP0Ou0e+/6RqyOhC+58jTp+FCy8ohNtrsANDhDK+9bHKQWfmDmPQw0TOJiKjxIfwye/qF7tZZf9KJE9fb7lBbh8hHfDSOMiALsgR6Bzaw2vGCIJ8hWjZCTQ8xljiE+edsSYkyf/Hfnyvlc8pNMDXp4iHx/47NT+geVwhxpVBYjE0+lmvZdX6WFCF1yP5DPjEI1tkWQxyDbY8YLMl7mAl9n2q+46V3AbuRWPBm8s+ev2BcYTR5wYWmC6BXSZpw== stefan@krikkit
    ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC1oM/869b9UCtbfGZv0jGcRUWTXVliS0QbzjOrVXNHWdP8M7WembEmYsAwxMeYCzIJJHdcdR4T833Rsr9rdPlOM3Lr9cuSSI8yqF4AUxtfh0jzPDfvIfuzqzrAjeg2bmwmYbkO5gbC9i8Zm8beSGkJwIFlc0dkHDJCaDefg45VJe4uDtLobpembzj+WEfd58z8bFqduBPPjIpx2bRHj9RVse7s+6ZLlEWxEdjLlfUHPXiIZoWVShimxPPB3PxfHj6qKzATeehYqRC3wUB/yCgGL8n24bAeusnZ2svUl1qUN99Wo8fLkyFtLtrfPAXacRTxc5rnIhvJCBOJ9yGMrMSiHqxaafcrKB6TxX8tj51hWjEsc7NtbJHGrirW/GUKN6Ycfx+gjc/2W+k15SyxsG4C1uO5TSgjo9Oh1FwRKX3HQ1uLw5CvjvcflFCW4+7xux9RXIzo94qf8NQCJ5RLzoppnJfb88ZG0KoL/qn47PjWA4Ue0KipKtaxbLysegd3iZcWfMJsxHv/vJiIyjYitAIc1DuTnqcHqp9Nk1HAKhVwH1/JJ4i0eWlf6b3XxyS9qs6DUWG9kURWwj3ylTvBLzd4Uu3Bl2E3n5jco/AeYd36dzwegow2vjZPuqLB5g0RC2TlGyWsMP/mx3qu5JCCsN6bLaZt3tCoXW7/nDxdT294+Q== stefan@arcturus
"""

# systemd-timesyncd
[[file]]
path    = "/etc/systemd/timesyncd.conf.d/hetzner.conf"
content = """
    [Time]
    NTP=ntp1.hetzner.de ntp2.hetzner.com ntp3.hetzner.net
"""

[[symlink]]
path   = "/etc/systemd/system/sysinit.target.wants/systemd-timesyncd.service"
target = "/usr/lib/systemd/system/systemd-timesyncd.service"

# pacman: put the Hetzner mirror in front
[[file]]
path    = "/usr/share/holo/files/50-hetzner/etc/pacman.d/mirrorlist.holoscript"
mode    = "0755"
content = """
    #!/bin/sh
    echo 'Server = http://mirror.hetzner.de/archlinux/$repo/os/$arch'
    cat
"""

# haveged
[[symlink]]
path   = "/etc/systemd/system/multi-user.target.wants/haveged.service"
target = "/usr/lib/systemd/system/haveged.service"

# some other configuration files that were generated by Hetzner's installimage
[[file]]
path    = "/etc/modprobe.d/blacklist-hetzner.conf"
content = """
    ### Hetzner Online GmbH - installimage
    ### silence any onboard speaker
    blacklist pcspkr
    blacklist snd_pcsp
    ### i915 driver blacklisted due to various bugs
    ### especially in combination with nomodeset
    blacklist i915
    ### mei driver blacklisted due to serious bugs
    blacklist mei
    blacklist mei-me
"""

[[file]]
path    = "/etc/sysctl.d/99-hetzner.conf"
content = """
    ### Hetzner Online GmbH installimage
    # sysctl config
    #net.ipv4.ip_forward=1
    net.ipv4.conf.all.rp_filter=1
    net.ipv4.icmp_echo_ignore_broadcasts=1
    # ipv6 settings (no autoconfiguration)
    net.ipv6.conf.default.autoconf=0
    net.ipv6.conf.default.accept_dad=0
    net.ipv6.conf.default.accept_ra=0
    net.ipv6.conf.default.accept_ra_defrtr=0
    net.ipv6.conf.default.accept_ra_rtr_pref=0
    net.ipv6.conf.default.accept_ra_pinfo=0
    net.ipv6.conf.default.accept_source_route=0
    net.ipv6.conf.default.accept_redirects=0
    net.ipv6.conf.default.forwarding=0
    net.ipv6.conf.all.autoconf=0
    net.ipv6.conf.all.accept_dad=0
    net.ipv6.conf.all.accept_ra=0
    net.ipv6.conf.all.accept_ra_defrtr=0
    net.ipv6.conf.all.accept_ra_rtr_pref=0
    net.ipv6.conf.all.accept_ra_pinfo=0
    net.ipv6.conf.all.accept_source_route=0
    net.ipv6.conf.all.accept_redirects=0
    net.ipv6.conf.all.forwarding=0
    vm.swappiness=0
"""

[[file]]
path    = "/usr/share/holo/files/50-hetzner/etc/resolv.conf"
content = """
    ### Hetzner Online GmbH installimage
    # nameserver config
    nameserver 213.133.100.100
    nameserver 213.133.99.99
    nameserver 213.133.98.98
    nameserver 2a01:4f8:0:a0a1::add:1010
    nameserver 2a01:4f8:0:a102::add:9999
    nameserver 2a01:4f8:0:a111::add:9898
"""
