[package]
name        = "hologram-automation"
version     = "0.5.1"
description = "hologram: infrastructure for dialog-based task automation and common tasks"

requires = [
    "secrets", # this uses /usr/bin/replicator
    "xmpp-bridge>=0.6",
]

[[file]]
path = "/usr/bin/with-xmpp-bridge"
mode = "0700" # needs to be protected from non-root because of embedded credentials
content = '''
    #!/bin/bash
    set -e

    # ensure that only one XMPP user runs at a time
    exec 9>/run/xmpp-bridge.lock
    flock 9

    export XMPPBRIDGE_JID="{{.Vars.xmpp.jid}}"
    export XMPPBRIDGE_PEER_JID="{{.Vars.xmpp.peer_jid}}"
    export XMPPBRIDGE_PASSWORD="{{.Vars.xmpp.password}}"
    xmpp-bridge -- "$@"
'''

[[symlink]]
path   = "/usr/share/holo/files/99-vars/usr/bin/with-xmpp-bridge.holoscript"
target = "/usr/bin/replicator"

################################################################################
# task: guided system upgrade

[[file]]
path = "/usr/lib/automation/upgrade.sh"
mode = "0755"
contentFrom = "src/automation-upgrade.sh"

[[file]]
path = "/usr/lib/systemd/system/auto-upgrade.service"
content = '''
    [Unit]
    Description=Guided automatic system upgrade
    After=multi-user.target
    Wants=multi-user.target

    [Service]
    Type=oneshot
    ExecStart=/usr/bin/with-xmpp-bridge /usr/lib/automation/upgrade.sh
'''

[[file]]
path = "/usr/lib/systemd/system/auto-upgrade.timer"
content = '''
    [Unit]
    Description=Guided automatic system upgrade

    [Timer]
    OnCalendar=15:00:00

    [Install]
    WantedBy=timers.target
'''

[[symlink]]
path   = "/etc/systemd/system/timers.target.wants/auto-upgrade.timer"
target = "/usr/lib/systemd/system/auto-upgrade.timer"

################################################################################
# task: health check (periodically, and immediately after a reboot)

[[file]]
path = "/usr/lib/automation/health.sh"
mode = "0755"
contentFrom = "src/automation-health.sh"

[[file]]
path = "/usr/lib/systemd/system/auto-health.service"
content = '''
    [Unit]
    Description=Automatic system health check
    After=multi-user.target
    Wants=multi-user.target

    [Service]
    Type=oneshot
    ExecStart=/usr/bin/with-xmpp-bridge /usr/lib/automation/health.sh
'''

[[file]]
path = "/usr/lib/systemd/system/auto-health.timer"
content = '''
    [Unit]
    Description=Automatic system health check

    [Timer]
    OnStartupSec=1min
    OnCalendar=17:00:00

    [Install]
    WantedBy=timers.target
'''

[[symlink]]
path   = "/etc/systemd/system/timers.target.wants/auto-health.timer"
target = "/usr/lib/systemd/system/auto-health.timer"
