[package]
name        = "holodeck-krikkit"
version     = "20161202.1"
description = "holodeck: services on Krikkit"
requires    = [
    "holo>=0.10",
    "hologram-kde-desktop",
    "hologram-dev-tools",
    "hologram-games",
    "hologram-dtp",
    "hologram-remount-efivarfs",
    "hologram-common-identity",
    # hardware support
    "intel-ucode",
    "xf86-input-synaptics",
    # support for Intel GPU
    "xf86-video-intel",
    "libva-intel-driver",
    "vulkan-intel",
    "vulkan-icd-loader",
    "lib32-vulkan-intel",
    "lib32-vulkan-icd-loader",
    # applications
    "kdeconnect",
    "libreoffice-still",
    "mpd",
    "plasma-nm",     # skipped in hologram-kde-desktop
    "powerdevil",    # skipped in hologram-kde-desktop
    "virtualbox",
    "linux-headers", # for virtualbox-host-dkms
]

[[file]]
path    = "/etc/hostname"
content = "krikkit"

[[file]]
path    = "/etc/profile.d/prettyprompt.sh"
content = """
export PRETTYPROMPT_COMMONUSER=stefan
export PRETTYPROMPT_HOSTCOLOR='0;32'
"""

# enable VirtualBox for my user account
[[user]]
name = "stefan"
groups = ["vboxusers"]

# Xorg: enable palm detection on touchpad
[[file]]
path    = "/etc/X11/xorg.conf.d/52-palm-detection.conf"
content = """
Section "InputClass"
    Identifier "touchpad enable palm detection"
    Driver "synaptics"
    MatchIsTouchpad "on"
    MatchDevicePath "/dev/input/event*"
    Option "PalmDetect" "on"
    Option "PalmMinWidth" "4"
    Option "PalmMinZ" "1"
    Option "TapButton1" "1"
    Option "TapButton2" "2"
    Option "TapButton3" "3"
EndSection
"""

# enable NetworkManager.service
[[symlink]]
path   = "/etc/systemd/system/multi-user.target.wants/NetworkManager.service"
target = "/usr/lib/systemd/system/NetworkManager.service"
[[symlink]]
path   = "/etc/systemd/system/dbus-org.freedesktop.NetworkManager.service"
target = "/usr/lib/systemd/system/NetworkManager.service"
[[symlink]]
path   = "/etc/systemd/system/dbus-org.freedesktop.nm-dispatcher.service"
target = "/usr/lib/systemd/system/NetworkManager-dispatcher.service"

# /etc/pulse/default.pa: disable corking which would mute MPD while Mumble or Skype are running
[[file]]
path = "/usr/share/holo/files/50-krikkit/etc/pulse/default.pa.holoscript"
mode = "0755"
content = """
#!/bin/sh
sed '/load-module module-role-cork/d'
"""

[[file]]
path = "/etc/systemd/logind.conf.d/no-magic-suspend.conf"
content = """
[Login]
HandlePowerKey=ignore
HandleLidSwitch=ignore
"""
