[package]
name        = "holodeck-arcturus"
version     = "20161207.1"
description = "holodeck: services on Arcturus"

requires = [
    "hologram-kde-desktop",
    "hologram-dev-tools",
    "hologram-games",
    "hologram-uefi-bootloader-with-luks",
    "hologram-common-identity",
    "hologram-dtp",
    "hologram-automation",
    # support for Intel CPU/GPU
    "hologram-intel-ucode",
    # support for AMD GPU
    "xf86-video-amdgpu",
    "vulkan-radeon",
    "lib32-vulkan-radeon",
    "vulkan-icd-loader",
    "lib32-vulkan-icd-loader",
    "mesa-libgl",
    "lib32-mesa-libgl",
    "mesa-vdpau",
    "lib32-mesa-vdpau",
    # network setup
    "broadcom-wl-dkms", # closed source driver because Linux kernel does not support my Wifi module
    "linux-headers",    # optional dep for broadcom-wl-dkms
    "wpa_supplicant",
    # additional apps
    "kdeconnect",
]

# identity

[[file]]
path    = "/etc/hostname"
content = "arcturus"

[[file]]
path    = "/etc/profile.d/prettyprompt.sh"
content = """
    export PRETTYPROMPT_COMMONUSER=stefan
    export PRETTYPROMPT_HOSTCOLOR='0;37'
"""

# network setup: systemd-networkd

[[file]]
path    = "/etc/systemd/network/lan.network"
content = """
    [Match]
    Name=en*

    [Network]
    Address=10.0.0.2/24
    Gateway=10.0.0.1
    DNS=10.0.0.1
"""

[[file]]
path    = "/etc/systemd/network/wlan.network"
content = """
    [Match]
    Name=wlp3s0

    [Network]
    Address=10.0.1.2/24
    DNS=10.0.1.1
"""

# network setup: systemd-resolved

[[symlink]]
path   = "/etc/systemd/system/multi-user.target.wants/systemd-resolved.service"
target = "/usr/lib/systemd/system/systemd-resolved.service"

[[symlink]]
path   = "/usr/share/holo/files/50-arcturus/etc/resolv.conf"
target = "/run/systemd/resolve/resolv.conf"

# network setup: wpa_supplicant

[[symlink]]
path   = "/etc/systemd/system/multi-user.target.wants/wpa_supplicant@wlp3s0.service"
target = "/usr/lib/systemd/system/wpa_supplicant@.service"

[[file]]
path    = "/etc/wpa_supplicant/wpa_supplicant-wlp3s0.conf"
content = """
    network={
        ssid="${DAMOGRAN_WLAN_SSID}"
        psk="${DAMOGRAN_WLAN_PSK}"
    }
"""
[[symlink]]
path   = "/usr/share/holo/files/50-arcturus-vars/etc/wpa_supplicant/wpa_supplicant-wlp3s0.conf.holoscript"
target = "/my/variables"
