[package]
name        = "holodeck-arcturus"
version     = "20160812.1"
description = "holodeck: services on Arcturus"

requires = [
    "hologram-kde-desktop",
    "hologram-dev-tools",
    "hologram-games",
    "hologram-uefi-bootloader",
    "hologram-common-identity",
    "hologram-dtp",
    # support for Intel CPU/GPU
    "hologram-intel-ucode",
    "xf86-video-intel",
    "libva-intel-driver",
    # support for AMD GPU
    "xf86-video-amdgpu",
    # network setup
    "broadcom-wl-dkms", # closed source driver because Linux kernel does not support my Wifi module
    "linux-headers",    # optional dep for broadcom-wl-dkms
    "wpa_supplicant",
    # additional apps
    "kdeconnect",
]

# identity

[[file]]
path    = "/etc/hostname"
content = "arcturus"

[[file]]
path    = "/etc/profile.d/prettyprompt.sh"
content = """
    export PRETTYPROMPT_COMMONUSER=stefan
    export PRETTYPROMPT_HOSTCOLOR='0;37'
"""

# boot loader (systemd-boot with encrypted root filesystem)

[[file]]
path    = "/usr/share/holo/files/50-arcturus/boot/loader/entries/arch.conf.holoscript"
mode    = "0755"
content = '''
    #!/bin/sh
    sed '/options/s+root=PARTUUID=\${PARTUUID}+cryptdevice=PARTUUID=${PARTUUID}:root:allow-discards root=/dev/mapper/root+'
'''

[[file]]
path    = "/usr/share/holo/files/50-arcturus/etc/mkinitcpio.conf.holoscript"
mode    = "0755"
content = """
    #!/bin/bash
    sed '
        s/^MODULES=""$/MODULES="amdgpu"/
        s/^HOOKS=.*$/HOOKS="base udev autodetect modconf block keymap keyboard encrypt filesystems fsck"/
    '
"""

[[action]]
on     = "setup"
script = "mkinitcpio -p linux"

# network setup: systemd-networkd

[[file]]
path    = "/etc/systemd/network/lan.network"
content = """
    [Match]
    Name=en*

    [Network]
    Address=10.0.0.2/24
    Gateway=10.0.0.1
    DNS=10.0.0.1
"""

[[file]]
path    = "/etc/systemd/network/wlan.network"
content = """
    [Match]
    Name=wlp3s0

    [Network]
    Address=10.0.1.2/24
    DNS=10.0.1.1
"""

# network setup: systemd-resolved

[[symlink]]
path   = "/etc/systemd/system/multi-user.target.wants/systemd-resolved.service"
target = "/usr/lib/systemd/system/systemd-resolved.service"

[[symlink]]
path   = "/usr/share/holo/files/50-arcturus/etc/resolv.conf"
target = "/run/systemd/resolve/resolv.conf"

# network setup: wpa_supplicant

[[symlink]]
path   = "/etc/systemd/system/multi-user.target.wants/wpa_supplicant@wlp3s0.service"
target = "/usr/lib/systemd/system/wpa_supplicant@.service"

[[file]]
path    = "/etc/wpa_supplicant/wpa_supplicant-wlp3s0.conf"
content = """
    network={
        ssid="${DAMOGRAN_WLAN_SSID}"
        psk="${DAMOGRAN_WLAN_PSK}"
    }
"""
[[symlink]]
path   = "/usr/share/holo/files/50-arcturus-vars/etc/wpa_supplicant/wpa_supplicant-wlp3s0.conf.holoscript"
target = "/my/variables"
