[package]
name        = "hologram-kde-desktop"
version     = "1.0.16"
description = "hologram: GUI installation with KDE Plasma desktop"

requires = [
    "hologram-kde-desktop-minimal",
    "hologram-base-gui",
    # desktop
    "mariadb", # optional: for Akonadi
    # KDE 5 applications
    "ark",
    "dolphin",
    "gwenview",
    "kdialog",
    "kgpg",
    "kid3",
    "kwalletmanager",
    # KDE 4 applications
    "breeze-kde4",
]

# TODO: kwallet-pam
