[package]
name        = "hologram-kde-desktop"
version     = "1.1.0"
description = "hologram: GUI installation with KDE Plasma desktop"

requires = [
    "hologram-kde-desktop-minimal",
    "hologram-base-gui",
    # KDE 5 applications
    "ark",
    "dolphin",
    "gwenview",
    "kdialog",
    "kgpg",
    "kid3",
    "kwalletmanager",
    # KDE PIM
    "kaddressbook",
    "kmail",
    "korganizer",
    # KDE 4 applications
    "breeze-kde4",
    # helpers
    "qt5-imageformats",
]

# TODO: kwallet-pam
